; One application ID per row. Set an entry to false to disable it.

[Applications]
brave-browser=true
com.brave.Browser=true
com.google.Chrome=true
com.microsoft.Edge=true
com.vivaldi.Vivaldi=true
epiphany=true
falkon=true
firefox=true
floorp=true
google-chrome=true
google-chrome-stable=true
io.gitlab.librewolf-community=true
konqueror=true
librewolf=true
luakit=true
microsoft-edge=true
microsoft-edge-stable=true
midori=true
mullvad-browser=true
nyxt=true
opera=true
org.gnome.Epiphany=true
org.kde.falkon=true
org.mozilla.firefox=true
palemoon=true
qutebrowser=true
seamonkey=true
slimjet=true
tor-browser=true
vivaldi=true
vivaldi-stable=true
waterfox=true
zen-browser=true
