; One executable filename per row. Set an entry to false to disable it.

[Applications]
arc.exe=true
avastbrowser.exe=true
avgbrowser.exe=true
brave.exe=true
chrome.exe=true
chromium.exe=true
dragon.exe=true
duckduckgo.exe=true
epic.exe=true
firefox.exe=true
floorp.exe=true
iexplore.exe=true
iron.exe=true
librewolf.exe=true
maxthon.exe=true
msedge.exe=true
opera.exe=true
palemoon.exe=true
qutebrowser.exe=true
seamonkey.exe=true
slimjet.exe=true
vivaldi.exe=true
waterfox.exe=true
zen.exe=true
